language: c
compiler: gcc

before_install:
    - sudo add-apt-repository -y 'ppa:zoogie/sdl2-snapshots'
    - sudo apt-get update -qq
    - sudo apt-get install -y libsdl-ttf2.0-dev libsdl2-dev

script: ./build.sh

notifications:
        email: false
